fixed bash scripts

diff --git a/bin/search b/bin/search
--- a/bin/search
+++ b/bin/search
@@ -2,68 +2,64 @@
 
 SEARCH_DB="var/search.sqlite3"
 SEARCH_LOG="var/log/search.log"
-SEARCH_CMD="flask --app search run --host 0.0.0.0 --port 8000"
-INDEX_CMD="./bin/index"
-PGREP_CMD="pgrep -f '$SEARCH_CMD'"
+FLASK_RUN_CMD="flask --app search run --host 0.0.0.0 --port 8000"
+INDEX_STATUS_CMD="./bin/index status"
 
-start_search() {
-    if [ ! -f "$SEARCH_DB" ]; then
-        echo "Error: can't find search database $SEARCH_DB"
-        echo "Try: ./bin/searchdb create"
-        exit 1
-    fi
-
-    if ! $INDEX_CMD status > /dev/null; then
-        echo "Error: index server is not running"
-        echo "Try $INDEX_CMD start"
-        exit 1
-    fi
-
-    if $PGREP_CMD > /dev/null; then
-        echo "Error: search server is already running"
-        exit 1
-    fi
-
+start_server() {
     echo "starting search server ..."
     mkdir -p var/log
-    rm -f "$SEARCH_LOG"
-    $SEARCH_CMD &> "$SEARCH_LOG" &
+    rm -f $SEARCH_LOG
+    $FLASK_RUN_CMD &> $SEARCH_LOG &
 }
 
-stop_search() {
+stop_server() {
     echo "stopping search server ..."
-    pkill -f "$SEARCH_CMD" || true
+    pkill -f "$FLASK_RUN_CMD" || true
 }
 
-status_search() {
-    if $PGREP_CMD > /dev/null; then
-        echo "search server running"
-        exit 0
-    else
-        echo "search server stopped"
-        exit 1
-    fi
+check_search_running() {
+    pgrep -f "$FLASK_RUN_CMD" > /dev/null
 }
 
-restart_search() {
-    stop_search
-    start_search
+check_index_running() {
+    $INDEX_STATUS_CMD
 }
 
 case "$1" in
     start)
-        start_search
+        if [ ! -f "$SEARCH_DB" ]; then
+            echo "Error: can't find search database $SEARCH_DB"
+            echo "Try: ./bin/searchdb create"
+            exit 1
+        fi
+        if ! check_index_running; then
+            echo "Error: index server is not running"
+            echo "Try ./bin/index start"
+            exit 1
+        fi
+        if check_search_running; then
+            echo "Error: search server is already running"
+            exit 1
+        fi
+        start_server
         ;;
     stop)
-        stop_search
+        stop_server
         ;;
     restart)
-        restart_search
+        stop_server
+        start_server
         ;;
     status)
-        status_search
+        if check_search_running; then
+            echo "search server running"
+            exit 0
+        else
+            echo "search server stopped"
+            exit 1
+        fi
         ;;
-    *)
+  *)
         echo "Usage: $0 {start|stop|restart|status}"
         exit 1
         ;;
